### ISSUE TITLE
Question: Submodule

### ISSUE THREAD

**Issue by 9glenda** [nixlang-wiki/nixos-landscape#15]
Why do we use a git submodule for the source code of landscape2? 
The fork of landscape2 has no changes but I assume this is subject to change. Personally I'd **highly** reccomend deleting the fork and creating a non fork repo because github restricts forks (no issues, code search...). You can do the git magic locally with a second upstream... (You'll figure out). 

Shouldn't dependencies be handled by the flake?

**Comment by cafkafk** [comment]
I'll eventually file a ticket with github to have them detach the fork, but then again, perhaps having issues centralized to this repository would be better. 

I already have some local changes to the fork I haven't pushed yet.
