### ISSUE TITLE
Idea: Use flakes and modules to decentralize content

### ISSUE THREAD

**Issue by hugosenari** [nixlang-wiki/nixos-landscape#22]
This is a random idea:

Accept only PR for flake.nix to add inputs, 
Where every new input should output landscape-modules, 
That we import to generate data.yml with evalModules.

And run an action every day to update lock.

**Comment by cafkafk** [comment]
The problem would be that those inputs could be changed at any time, changing the contents of the landscape.

**Comment by hugosenari** [comment]
> inputs could be changed at any time, changing the contents of the landscape.

That will be the cool part of this idea.
Orgs like nixos, nix-community, cachix, detSys, numide can add any new project without our interaction, changing theirs icons, urls, description, etc.

I agree with risk concerns:
- Bad content (unpolite content)
- Bad code (breaking build)
- Conflicts/Duplications (two inputs trying to add same item)


But is just a random idea for the future.

Closing as note planned ;-)
