### ISSUE TITLE
Bad rendering on Firefox

### ISSUE THREAD

**Issue by hugosenari** [nixlang-wiki/nixos-landscape#43]
In Firefox the page script takes too long to complete, then Firefox request to stop the script and left the page without correctly rendering it.
Maybe is an upstrem bug, I'm not sure if is there any other changes after #42 but could be related to the amount of data.

It works in chrome

**Comment by cafkafk** [comment]
What version of firefox are you on, it seems to work for me?

**Comment by hugosenari** [comment]
121.0

But it is strange, I have two machines, both with same version (NixOS), with addon in sync, and it only fails in one.
Closing it as Heisenbug

**Comment by cafkafk** [comment]
> 121.0
> 
> But it is strange, I have two machines, both with same version (NixOS), with addon in sync, and it only fails in one. Closing it as Heisenbug

It's still very odd thou... >_>

I did deploy a newer version of landscape2 IIRC, maybe something upstream broke... I might investigate after work.
