### ISSUE TITLE
Add flake libary liks

### ISSUE THREAD

**Issue by 9glenda** [nixlang-wiki/nixos-landscape#6]
Following flake libs should be added considering their popularity:
- [x] [flake-utils](https://github.com/numtide/flake-utils) 
- [x] [flake-parts](https://flake.parts/)

**Comment by cafkafk** [comment]
:+1:  If no one does it I'll do it eventually

**Comment by cafkafk** [comment]
This was finalized in 7288b34456f1ad168d130d2be864c137da2a510a
