### ISSUE TITLE
Github Icon point to wrong project

### ISSUE THREAD

**Issue by hugosenari** [nixlang-wiki/nixos-landscape#7]
First,
Thank you for setting this up =)

The icon for github project in the site is pointing to CNCF version, that may lead to some confusion for those want to contribute, adding more links.

**Comment by cafkafk** [comment]
They don't seem to expose any ways to change this, so we'll have to do this in https://github.com/nixlang-wiki/landscape2 I think

**Comment by hugosenari** [comment]
Now I am confused, what we are using? :-D

**Comment by cafkafk** [comment]
Fixed in #30
